- debug: msg="/etc/hosts"

- shell: grep ldap.{{domain}}.{{tld}} /etc/ssh/sshd_config
  register: hostname_exists
  ignore_errors: True

- lineinfile: dest=/etc/hosts  insertafter="EOF" line="{{ldap_ipv4}}  ldap.{{domain}}.{{tld}}"
  when: hostname_exists|failed
