- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes

- name: Install pkgs
  apt:
    pkg:
    - vim
    - python3
    - python3-dev
    - python3-pip
    - git

    
